/*
* generated by Xtext
*/
package mdse.book.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import mdse.book.services.SWMLGrammarAccess;

public class SWMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SWMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected mdse.book.parser.antlr.internal.InternalSWMLParser createParser(XtextTokenStream stream) {
		return new mdse.book.parser.antlr.internal.InternalSWMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "WebModel";
	}
	
	public SWMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SWMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
