/*
* generated by Xtext
*/
package mdse.book.ui.contentassist;

import mdse.book.ui.contentassist.AbstractSWMLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SWMLProposalProvider extends AbstractSWMLProposalProvider {

}
