/*
 * generated by Xtext
 */
package mdse.book.ui.contentassist

import mdse.book.ui.contentassist.AbstractSWMLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SWMLProposalProvider extends AbstractSWMLProposalProvider {
}
