/**
 * generated by Xtext
 */
package mdse.book.validation;

import mdse.book.validation.AbstractSWMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SWMLValidator extends AbstractSWMLValidator {
}
