/*
 * generated by Xtext
 */
package mdse.book.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SWMLUiModule extends mdse.book.ui.AbstractSWMLUiModule {
	public SWMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
