/*
 * generated by Xtext
 */
package mdse.book.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSWMLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(mdse.book.sWML.SWMLPackage.eINSTANCE);
		return result;
	}
}
