/*
 * generated by Xtext
 */
package mdse.book.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SWMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return mdse.book.ui.internal.SWMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return mdse.book.ui.internal.SWMLActivator.getInstance().getInjector("mdse.book.SWML");
	}
	
}
