/*
 * generated by Xtext
 */
package mdse.book.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import mdse.book.ui.internal.SWMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SWMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SWMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SWMLActivator.getInstance().getInjector(SWMLActivator.MDSE_BOOK_SWML);
	}
	
}
