<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="swml" nsURI="http://www.mdse-book.org/swml/" nsPrefix="swml">
  <eAnnotations source="gmf">
    <details key="foo" value="bar"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="WebModel">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hypertext" lowerBound="1"
        eType="#//HypertextLayer" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        eType="#//ContentLayer" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HypertextLayer">
    <eAnnotations source="gmf.node">
      <details key="label" value="Hypertext"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" lowerBound="1" upperBound="-1"
        eType="#//Page" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="homePage" lowerBound="1"
        eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentLayer">
    <eAnnotations source="gmf.node">
      <details key="label" value="Content"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" lowerBound="1"
        upperBound="-1" eType="#//Class" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representativeAttribute"
        lowerBound="1" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SWMLTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rounded"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPage" eSuperTypes="#//DynamicPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetailsPage" eSuperTypes="#//DynamicPage"/>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicPage" abstract="true" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayedClass" lowerBound="1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticPage" eSuperTypes="#//Page"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true">
    <eAnnotations source="gmf.link">
      <details key="target" value="target"/>
      <details key="style" value="solid"/>
      <details key="target.decoration" value="filledclosedarrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NCLink" eSuperTypes="#//Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="CLink" eSuperTypes="#//Link"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SWMLTypes">
    <eLiterals name="Boolean"/>
    <eLiterals name="String" value="1"/>
    <eLiterals name="Integer" value="2"/>
    <eLiterals name="Float" value="3"/>
    <eLiterals name="Email" value="4"/>
  </eClassifiers>
</ecore:EPackage>
