/*
* generated by Xtext
*/
package mdse.book.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SWMLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
