/*
 * generated by Xtext
 */
package mdse.book;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SWMLRuntimeModule extends mdse.book.AbstractSWMLRuntimeModule {

}
