<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sWML"
    nsURI="http://www.mdse-book.org/SWML" nsPrefix="sWML">
  <eClassifiers xsi:type="ecore:EClass" name="WebModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hypertext" eType="#//HypertextLayer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//ContentLayer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HypertextLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//IndexPage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayedClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SWMLTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SWMLTypes">
    <eLiterals name="String" literal="String"/>
    <eLiterals name="Integer" value="1" literal="Integer"/>
    <eLiterals name="Float" value="2" literal="Float"/>
    <eLiterals name="Email" value="3" literal="Email"/>
    <eLiterals name="Boolean" value="4" literal="Boolean"/>
  </eClassifiers>
</ecore:EPackage>
